services:

  loggen:
    build:
      context: loggen/
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
        storeId: 10
    image: dec_loggen:latest
    volumes:
      - app1-vol:/usr/share/app
    
  filebeat:
    build:
      context: filebeat/
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
    image: dec_filebeat:latest
    command: filebeat -e -strict.perms=false
    volumes:
      - app1-vol:/usr/share/app
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    depends_on:
      - loggen

volumes:
  app1-vol:
